### ISSUE TITLE
Question about code implementation

### ISSUE THREAD

**Issue by junhyeokahn** [kzl/aop#1]
Hello!

Thanks for your effort in maintaining this repository.
I have a quick question in your implementation.
[Here](https://github.com/kzl/aop/blob/732fd1ee48a4ebf93fcf1c6153de909f98eab66f/utils/traj.py#L156), why do you clip the action with -1 and 1 instead of max_input and min_input?
I don't see any denormalization inside the step function and if you just apply the input between -1 and 1, the environment will not generate useful trajectory.

**Comment by kzl** [comment]
Hi,

Thanks for your interest! It is true that at some point there should be a
denormalizing step, but because all the environments in this project only
required actions between -1 and 1, it was not an issue. Thanks for pointing
this out, it'll probably be fixed later.

Best wishes,

Kevin

**Comment by junhyeokahn** [comment]
Thanks for the reply!
That makes sense.

For the normal case, can I just comment out the clipping part? 
Or do you still recommend using the actions between -1 and 1 and denormalize in the ```step()``` method in the environment?
In other words, are the values of the filter coefficients only proper for the action in between -1 or 1?
Can I use the same filter coefficients for non-normalized action space to generate randomness?

**Comment by kzl** [comment]
Personally, I would recommend making sure the environment itself is
normalized, which is generally standard practice. Otherwise, you have to
tune hyperparameters and analyze statistics from a different range (for
example, the variance of the MPC trajectories/labeled filter_coefs in this
code would have to adjust per environment). But, you can comment out the
clipping part if you want.

In particular, for this codebase, the filter_coefs = (sigma, beta_1,
beta_2, beta_3), where sigma is used to generate Gaussian noise. If the
action is not in (-1, 1), then sigma would have to be scaled appropriately,
but the beta values could stay the same.

**Comment by junhyeokahn** [comment]
Thanks this makes a lot of sense!

**Comment by junhyeokahn** [comment]
Hello, I have one more additional question regarding filter coefficients.
I see that you are using these numbers for the filter coefficients (please see this [line](https://github.com/kzl/aop/blob/732fd1ee48a4ebf93fcf1c6153de909f98eab66f/params/default_params.py#L47)).
What is the rationale of using these numbers?

If you use lambda value as 0.1, the exponential distribution looks like the below figure:
<img width="1313" alt="Screen Shot 2020-03-25 at 10 57 50 PM" src="https://user-images.githubusercontent.com/23005104/77608773-2af11000-6eec-11ea-90b3-8588b3cd561d.png">
, which could result in large sigma value (for example sigma could be sampled as 10).
Then the normal distribution with ```sigma=10``` would be the following figure:
<img width="1400" alt="Screen Shot 2020-03-25 at 11 01 43 PM" src="https://user-images.githubusercontent.com/23005104/77608964-a6eb5800-6eec-11ea-82e5-1384bd4c8675.png">

Then, the magnitude of [```eps```](https://github.com/kzl/aop/blob/732fd1ee48a4ebf93fcf1c6153de909f98eab66f/utils/traj.py#L149) could be easily larger than 1, which is not proper noise for normalized action.
Would the proper statistics of ```eps``` for normalized action be just a normal distribution with ```sigma=1```?

**Comment by kzl** [comment]
Oh, thanks for pointing this out. This was actually an old version of the
traj.py file that I incorrectly uploaded. The first filter coefficient
should be sigma (which should be 0.1). I don't think it actually matters
much in practice, but that is a problem that would arise. I'll push the
corrected version. Thanks!

**Comment by junhyeokahn** [comment]
Thanks for the quick and clear answer!
